version: "3.1"

services:
  db:
    image: mariadb:10.3
    container_name: voterigth_db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8888:80
    environment:
      - PMA_ARBITRARY=1
  
  backend: 
    image: nginx:1.22-alpine
    ports:
      - "3333:80"
    volumes: 
      - ./backend:/backend
      - ./backend/config/nginx.conf:/etc/nginx/nginx.conf

  php: 
    build: 
      context: .
      dockerfile: Dockerfile  # Ajoutez cette ligne
    volumes: 
      - ./backend:/backend

volumes:
  dbdata: