-- Insertions réalisées
INSERT INTO comment (COM_id_NB, COM_message_VC, COM_proposal_NB, COM_sender_NB, COM_moderator_NB) VALUES
-- Commentaires normaux
(1, 'C''est une suggestion intéressante, je pense qu''elle mérite qu''on y réfléchisse.', 38, 53, NULL),
(2, 'Bonne idée, cette proposition.', 56, 57, NULL),
(3, 'D''accord pour cette idée, mais y a des points à éclaircir.', 31, 17, NULL),
(4, 'Super initiative, je la soutiens à fond.', 28, 98, NULL),
(5, 'Idée prometteuse, on devrait l''étudier de plus près.', 54, 7, NULL),
(6, 'Pas d''objection pour moi, ça a l''air cohérent.', 2, 54, NULL),
(7, 'Ouais, la plage est vraiment sale depuis le dernier festival.', 28, 41, NULL),
(8, 'Ouais, c''est sûr qu''il y a encore pas mal de zones d''ombre pour l''instant.', 31, 20, NULL),
(9, 'Cette idée pourrait donner de bons résultats, allons-y.', 40, 53, NULL),
(10, 'Je suis d''accord, de toute façon on est en retard.', 45, 28, NULL),
(11, 'Il nous faut absolument une réponse dans 2 jours.', 43, 6, NULL),
(12, 'Je suis d''accord avec toi.', 43, 27, NULL),
(13, 'Les élèves ont des lacunes, une remise à niveau leur ferait du bien.', 20, 40, NULL),
(14, 'C''est une bonne idée, ça fait longtemps qu''on n''a pas fait de musée.', 3, 18, NULL),
(15, 'On est un peu en retard, faut décider vite.', 43, 58, NULL),
(16, 'L''organisation m''a l''air pas mal, donc ok pour moi.', 35, 77, NULL),
(17, 'Franchement, j''ai un doute, on doit voter.', 58, 95, NULL),
(18, 'L''organisation me paraît correcte.', 46, 59, NULL),
(19, 'Je soutiens complètement cette initiative, c''est un beau projet.', 52, 7, NULL),
(20, 'Bonne idée pour la conférence.', 7, 13, NULL),
(21, 'En théorie, l''idée est bonne, mais faudra acheter du matos.', 8, 13, NULL),
(22, 'C''est une bonne idée qui pourrait apporter des retours intéressants.', 32, 97, NULL),
(23, 'Je suis d''accord, faut qu''on fasse quelque chose.', 28, 69, NULL),
(24, 'Ça me semble correct si le calendrier le permet.', 45, 30, NULL),
(25, 'Bonne initiative, je pense que tout le monde est d''accord.', 15, 100, NULL),
(26, 'J''ai vraiment pas envie mais ça fait 6 mois que je l''ai pas fait.', 41, 20, NULL),
(27, 'Pourquoi pas, c''est la tradition après tout.', 2, 23, NULL),
(28, 'Bonne suggestion, ça semble être un bon complément.', 11, 51, NULL),
(29, 'C''est une super initiative.', 37, 49, NULL),
(30, 'D''accord, avançons en mettant en place une structure solide.', 19, 99, NULL),
(31, 'Oui, ça pourrait être un bon évènement pour les fêtes.', 34, 90, NULL),
(32, 'Excellente idée, trop de personnes sont négligentes.', 6, 80, NULL),
(33, 'Je ne suis pas opposé à cette idée.', 51, 67, NULL),
(34, 'Certains clubs vont vraiment être surpris par notre niveau.', 10, 63, NULL),
(35, 'Je soutiens, veillons simplement aux ressources.', 17, 89, NULL),
(36, 'Pas de souci pour moi non plus.', 2, 25, NULL),
(37, 'Je trouve que cette proposition va nous coûter un bras.', 39, 44, NULL),
(38, 'Idée faisable, mais il faudra bien cadrer.', 16, 100, NULL),
(39, 'En accord, mais il reste des contraintes à résoudre par rapport au parking.', 23, 61, NULL),
(40, 'Effectivement, c''est une connaissance de base pour tout expert qui se respecte.', 27, 70, NULL),
(41, 'Cette idée a du potentiel, mais il faut voir le budget.', 1, 25, NULL),
(42, 'T''abuses, tu t''es pas dit qu''à un moment faudra que tu la fasses.', 41, 2, NULL),
(43, 'Je trouve qu''il n''y a vraiment pas assez de points de ravitaillement.', 50, 72, NULL),
(44, 'Oui, ça semble aligné avec nos objectifs.', 4, 76, NULL),
(45, 'Pas d''objection, c''est pertinent.', 6, 76, NULL),
(46, 'Oui, je suis aussi très sceptique à propos de cette idée.', 31, 86, NULL),
(47, 'Il faudrait revoir certaines normes de sécurité, mais sinon ok.', 46, 71, NULL),
(48, 'Le salon des expositions me paraît être une idée tout à fait adaptée.', 44, 55, NULL),
(49, 'Pour moi, le parcours est bien, ça change de l''année dernière.', 48, 72, NULL),
(50, 'C''est faisable, mais avec une planification rigoureuse.', 49, 65, NULL),
-- Commentaires signalés et épinglés par le modérateur du groupe
(51, 'On ne devrait pas aider les gens dans le besoin, ils se sont mis tout seuls dans la merde.', 37, 49, 19),
(52, 'Les ateliers d''amélioration c''est pour les faibles, vous tous en fait.', 13, 35, 94),
(53, 'N''hésitez pas à me joindre au 0769503412 pour des réductions exclusives sur poltronesofa.', 14, 38, 94),
(54, 'Faudra que les danseuses portent des tenues légères sinon moi je viens pas.', 2, 25, 47),
(55, 'Vraiment la sensibilisation c''est un truc de gauchiste, les amendes c''est efficace.', 29, 41, 69),
(56, 'En fait t''es un déchet, c''est toi qu''on va ramasser sur la plage.', 29, 98, 69),
(57, 'Impatient de pouvoir défoncer les abrutis de la ville d''à côté.', 10, 51, 63),
(58, 'Faut pas les laisser respirer, ces bâtards sont super arrogants.', 10, 51, 63),
(59, 'Je pense que je vais ramener une voiture électrique pour le rassemblement, les gars.', 23, 39, 61),
(60, 'Vous voudriez pas qu''on ouvre un peu plus notre garage à des voitures électriques.', 22, 39, 61);